@startuml　クラス図 
class Knapsack{
    -int capacity
    +int capacity_get()
    +int capacity_set(int input)
}
class Item{
    -int value
    -int weight
    +int value_get()
    +int value_set(int input)
    +int weight_get()
    +int weight_set(int input)
}

class Item_list{
    -item *item
    +int list_Create(int input)
    +int item_list_get(int Item_number)

    +int item_list_set(Item item,int Item_number)
    +int item_length()
}

class Sum{
    -static int dp_table[100][100010]
    -int maxSum
    -int dp_table_get(int Item_number,int knapsack_weight)
    -int dp_table_set(int Item_number,int knapsack_weight,int value)
    +int maxSum_updata(int Item_number,int knapsack_weight)
    +int dp_max()
}
@enduml