@startuml　クラス図 
class Knapsack{
    -int capacity
    +int capacity_get()
    +int capacity_set(int input_capacity)
}
class Item{
    -int value
    -int weight
    +int value_get()
    +int value_set(int input_value)
    +int weight_get()
    +int weight_set(int input_weight,int input_capacity)
}

class Item_list{
    -int *item_list
    +int list_create(int input_list_max)
    +int list_get(int Item_number)
    +int list_set(Item item,int Item_number)
    +int list_length()
}

class Dp{
    -int dp_table[110][100010]
    -int dp_table_get(int item_number,int knapsack_weight)
    -int dp_table_create()
    -int dp_table_set(int item_number,int knapsack_weight,int item_list_value)
    +int maxSum_updata(Item_list *item_list,Knapsack *knapsack)
    +int dp_max(Item_list *item_list,Knapsack *knapsack)
}

class main{
    -int input_capacity
    -int input_list_max
    -int input_value
    -int input_weight
    -int max_sum
}
@enduml